list(APPEND VULKAN_ENGINE_SOURCES
  # game
  game/entity.h
  game/entity.cpp
  game/entity_manager.h
  game/entity_manager.cpp
  game/game_world.h
  game/game_world.cpp

  # game/component
  game/component/component.h
  game/component/ship_controller.h
  game/component/ship_controller.cpp

  # game/input
  game/input/keybinds.h
  game/input/keybinds.cpp

  # game/orbit
  game/orbit/orbit_prediction_math.h
  game/orbit/orbit_prediction_math.cpp
  game/orbit/orbit_render_curve.h
  game/orbit/render_curve/orbit_render_curve_internal.h
  game/orbit/render_curve/orbit_render_curve.cpp
  game/orbit/render_curve/orbit_render_curve_render.cpp
  game/orbit/render_curve/orbit_render_curve_pick.cpp
  game/orbit/orbit_plot_util.h
  game/orbit/orbit_plot_util.cpp
  game/orbit/nbody/trajectory_utils.h
  game/orbit/nbody/trajectory_utils.cpp
  game/orbit/nbody/tuning.h
  game/orbit/nbody/types.h
  game/orbit/nbody/service.h
  game/orbit/nbody/service.cpp
  game/orbit/nbody/diagnostics.h
  game/orbit/nbody/internal.h
  game/orbit/nbody/prediction/compute.cpp
  game/orbit/nbody/prediction/routes.cpp
  game/orbit/nbody/prediction/spacecraft.cpp
  game/orbit/nbody/prediction/planned_route.cpp
  game/orbit/nbody/prediction/stage_publish.cpp
  game/orbit/nbody/prediction/planned_cache.cpp
  game/orbit/nbody/prediction/planned_maneuver.cpp
  game/orbit/nbody/prediction/chunk_attempt.cpp
  game/orbit/nbody/prediction/planned.cpp
  game/orbit/nbody/prediction/trajectory.cpp
  game/orbit/nbody/prediction/sampling.cpp
  game/orbit/nbody/prediction/policy_integrator.cpp
  game/orbit/nbody/prediction/policy_chunking.cpp
  game/orbit/nbody/prediction/policy_profile.cpp
  game/orbit/nbody/prediction/policy_adaptive.cpp
  game/orbit/nbody/prediction/policy_ephemeris.cpp
  game/orbit/kepler/README.md
  game/orbit/kepler/kepler_types.h
  game/orbit/kepler/kepler_prediction_options.h
  game/orbit/kepler/kepler_celestial_nbody.h
  game/orbit/kepler/kepler_celestial_nbody.cpp
  game/orbit/kepler/kepler_primary_resolver.h
  game/orbit/kepler/kepler_primary_resolver.cpp
  game/orbit/kepler/kepler_arc_builder.h
  game/orbit/kepler/kepler_arc_builder.cpp
  game/orbit/kepler/kepler_arc_line_builder.h
  game/orbit/kepler/kepler_arc_line_builder.cpp
  game/orbit/kepler/kepler_arc_info.h
  game/orbit/kepler/kepler_arc_info.cpp

  # game root
  game/main_game.h
  game/main_game.cpp

  # game/state
  game/state/game_state.h
  game/state/game_state.cpp
  game/state/game_state_manager.h
  game/state/game_state_manager.cpp

  # game/states
  game/states/title_screen_state.h
  game/states/title_screen_state.cpp
  game/states/gameplay_loading_state.h
  game/states/gameplay_loading_state.cpp
  game/states/pause_state.h
  game/states/pause_state.cpp
  game/states/settings_state.h
  game/states/settings_state.cpp

  # game/states/gameplay
  game/states/gameplay/gameplay_state.h
  game/states/gameplay/gameplay_state.cpp
  game/states/gameplay/settings/gameplay_preload_cache.h
  game/states/gameplay/settings/gameplay_preload_cache.cpp
  game/states/gameplay/ui/gameplay_state_ui.cpp
  game/states/gameplay/gameplay_state_orbit_prediction.cpp
  game/states/gameplay/prediction_kepler/gameplay_state_kepler_prediction.cpp
  game/states/gameplay/ui/gameplay_state_kepler_prediction_debug_ui.cpp
  game/states/gameplay/ui/gameplay_state_nbody_orbit_debug_ui.cpp
  game/states/gameplay/gameplay_state_scene.cpp
  game/states/gameplay/gameplay_state_sim.cpp
  game/states/gameplay/settings/gameplay_settings.h
  game/states/gameplay/settings/gameplay_settings.cpp
  game/states/gameplay/orbital/formation_hold_system.h
  game/states/gameplay/orbital/formation_hold_system.cpp
  game/states/gameplay/ui/frame_monitor.h
  game/states/gameplay/ui/frame_monitor.cpp
  game/states/gameplay/orbital/orbit_runtime.h
  game/states/gameplay/orbital/orbiter_state_bridge.h
  game/states/gameplay/orbital/orbiter_state_bridge.cpp
  game/states/gameplay/orbital/orbital_runtime_system.h
  game/states/gameplay/orbital/orbital_runtime_system.cpp
  game/states/gameplay/orbital/orbital_physics_system.h
  game/states/gameplay/orbital/orbital_physics_system.cpp
  game/states/gameplay/time_warp_state.h
  game/states/gameplay/prediction_nbody/gameplay_state_prediction_types.h
  game/states/gameplay/prediction_nbody/gameplay_prediction_context.h
  game/states/gameplay/prediction_nbody/gameplay_prediction_cache_internal.h
  game/states/gameplay/prediction_nbody/gameplay_prediction_cache_internal.cpp
  game/states/gameplay/prediction_nbody/prediction_trajectory_sampler.h
  game/states/gameplay/prediction_nbody/prediction_trajectory_sampler.cpp
  game/states/gameplay/prediction_nbody/prediction_frame_resolver.h
  game/states/gameplay/prediction_nbody/prediction_frame_resolver.cpp
  game/states/gameplay/prediction_nbody/prediction_frame_context_builder.h
  game/states/gameplay/prediction_nbody/prediction_frame_context_builder.cpp
  game/states/gameplay/prediction_nbody/prediction_frame_controller.h
  game/states/gameplay/prediction_nbody/prediction_frame_controller.cpp
  game/states/gameplay/prediction_nbody/prediction_frame_cache_builder.h
  game/states/gameplay/prediction_nbody/prediction_frame_cache_builder.cpp
  game/states/gameplay/prediction_nbody/prediction_metrics_builder.h
  game/states/gameplay/prediction_nbody/prediction_metrics_builder.cpp
  game/states/gameplay/prediction_nbody/nbody/chunk_assembly.h
  game/states/gameplay/prediction_nbody/nbody/chunk_assembly.cpp
  game/states/gameplay/prediction_nbody/gameplay_prediction_state.h
  game/states/gameplay/prediction_nbody/gameplay_prediction_state.cpp
  game/states/gameplay/prediction_nbody/gameplay_prediction_access.h
  game/states/gameplay/prediction_nbody/prediction_host_context.h
  game/states/gameplay/prediction_nbody/prediction_host_context_builder.h
  game/states/gameplay/prediction_nbody/prediction_host_context_builder.cpp
  game/states/gameplay/prediction_nbody/prediction_subject_state_provider.h
  game/states/gameplay/prediction_nbody/prediction_subject_state_provider.cpp
  game/states/gameplay/prediction_nbody/prediction_system.h
  game/states/gameplay/prediction_nbody/prediction_system.cpp
  game/states/gameplay/prediction_nbody/gameplay_prediction_derived_service.h
  game/states/gameplay/prediction_nbody/gameplay_prediction_derived_service.cpp
  game/states/gameplay/prediction_nbody/gameplay_state_prediction.cpp
  game/states/gameplay/prediction_nbody/gameplay_state_prediction_frames.cpp
  game/states/gameplay/prediction_nbody/runtime/gameplay_state_prediction_runtime_internal.h
  game/states/gameplay/prediction_nbody/runtime/prediction_track_lifecycle.h
  game/states/gameplay/prediction_nbody/runtime/prediction_lifecycle_reducer.h
  game/states/gameplay/prediction_nbody/runtime/prediction_lifecycle_reducer.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_runtime_context.h
  game/states/gameplay/prediction_nbody/runtime/prediction_window_policy.h
  game/states/gameplay/prediction_nbody/runtime/prediction_window_context_builder.h
  game/states/gameplay/prediction_nbody/runtime/prediction_window_context_builder.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_request_factory.h
  game/states/gameplay/prediction_nbody/runtime/prediction_request_factory.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_invalidation_controller.h
  game/states/gameplay/prediction_nbody/runtime/prediction_invalidation_controller.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_maneuver_invalidation.h
  game/states/gameplay/prediction_nbody/runtime/prediction_maneuver_invalidation.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_result_applier.h
  game/states/gameplay/prediction_nbody/runtime/prediction_result_applier.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_solver_result_applier.h
  game/states/gameplay/prediction_nbody/runtime/prediction_solver_result_applier.cpp
  game/states/gameplay/prediction_nbody/runtime/prediction_runtime_controller.h
  game/states/gameplay/prediction_nbody/runtime/prediction_runtime_controller.cpp
  game/states/gameplay/prediction_nbody/runtime/gameplay_state_prediction_runtime.cpp
  game/states/gameplay/prediction_nbody/runtime/gameplay_state_prediction_runtime_solver.cpp
  game/states/gameplay/prediction_nbody/runtime/gameplay_state_prediction_runtime_requests.cpp
  game/states/gameplay/prediction_nbody/runtime/gameplay_state_prediction_runtime_results.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_internal.h
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_helpers.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_prepare.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_render_helpers.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_shared.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_track.cpp
  game/states/gameplay/prediction_nbody/draw/gameplay_state_prediction_draw_pick.cpp
  game/states/gameplay/prediction_kepler/README.md
  game/states/gameplay/prediction_kepler/kepler_prediction_state.h
  game/states/gameplay/prediction_kepler/kepler_prediction_subject.h
  game/states/gameplay/prediction_kepler/kepler_prediction_subject.cpp
  game/states/gameplay/prediction_kepler/kepler_prediction_builder.h
  game/states/gameplay/prediction_kepler/kepler_prediction_builder.cpp
  game/states/gameplay/prediction_kepler/kepler_prediction_draw.h
  game/states/gameplay/prediction_kepler/kepler_prediction_draw.cpp
  game/states/gameplay/prediction_kepler/kepler_prediction_system.h
  game/states/gameplay/prediction_kepler/kepler_prediction_system.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_types.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_plan.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_plan.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_node_resolver.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_node_resolver.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_orbit_pick.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_orbit_pick.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_gizmo.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_gizmo.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_gizmo_controller.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_gizmo_controller.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_commands.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_commands.cpp
  game/states/gameplay/maneuver_kepler/kepler_maneuver_system.h
  game/states/gameplay/maneuver_kepler/kepler_maneuver_system.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_colors.h
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_types.h
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_util.h
  game/states/gameplay/maneuver_nbody/maneuver_plan_model.h
  game/states/gameplay/maneuver_nbody/maneuver_plan_model.cpp
  game/states/gameplay/maneuver_nbody/maneuver_commands.h
  game/states/gameplay/maneuver_nbody/maneuver_commands.cpp
  game/states/gameplay/maneuver_nbody/maneuver_controller.h
  game/states/gameplay/maneuver_nbody/maneuver_controller.cpp
  game/states/gameplay/maneuver_nbody/maneuver_gizmo_controller.h
  game/states/gameplay/maneuver_nbody/maneuver_gizmo_controller.cpp
  game/states/gameplay/maneuver_nbody/maneuver_prediction_bridge.h
  game/states/gameplay/maneuver_nbody/maneuver_prediction_bridge.cpp
  game/states/gameplay/maneuver_nbody/maneuver_ui_controller.h
  game/states/gameplay/maneuver_nbody/maneuver_system.h
  game/states/gameplay/maneuver_nbody/maneuver_system.cpp
  game/states/gameplay/maneuver_nbody/maneuver_runtime_cache_builder.h
  game/states/gameplay/maneuver_nbody/maneuver_runtime_cache_builder.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_gizmo.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_nodes.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_nodes_cache.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_panel.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_runtime.cpp
  game/states/gameplay/maneuver_nbody/gameplay_state_maneuver_ui.cpp
  game/states/gameplay/scenario/scenario_config.h
  game/states/gameplay/scenario/scenario_loader.h
  game/states/gameplay/scenario/scenario_loader.cpp

  # game/legacy
  game/legacy/example_game.h
  game/legacy/example_game.cpp
  game/legacy/rebasing_test_game.h
  game/legacy/rebasing_test_game.cpp
)
